### ISSUE TITLE
New update breaks mod

### ISSUE THREAD

**Issue by Draedon123** [WesCook/ForgotMyHat#2]
Mod does not work, most likely due to v1.3?11476 offline mod changes
![image](https://github.com/WesCook/ForgotMyHat/assets/118961726/97d42d62-eb28-43b3-8810-6362faf66507)

**Comment by WesCook** [comment]
Thanks for the bug report.  Indeed this update made a lot of offline calculation changes.  This should be fixed in v1.4.0 which just went out.
